apiVersion: skaffold/v1beta8
kind: Config
build:
  googleCloudBuild:
    projectId: dongdongchat
  artifacts:
  - image: gcr.io/dongdongchat/youtube-cron-job

deploy:
  kubectl:
    manifests:
      - k8s/*