apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: koreanow-regular-videos
spec:
  schedule: "*/15 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: koreanow-regular-videos
            image: gcr.io/dongdongchat/youtube-cron-job
            env:
              - name: FUNC_NAME
                value: "getVideosAndUpdateDB"
              - name: FUNC_PARAM
                value: "?&channelId=UCR-L8oZkHzgDh1ahJhH2WDQ&part=snippet&type=video&order=date&maxResults=5"
              - name: LIB_NAME
                value: "youtube"
            envFrom:
              - configMapRef:
                  name: firebase
              - configMapRef:
                  name: youtube-api-key-2
          restartPolicy: OnFailure
          hostNetwork: true
