apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: koreanunnie-regular-videos
spec:
  schedule: "*/15 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: koreanunnie-regular-videos
            image: gcr.io/jinjaio/youtube-cron-job
            env:
              - name: FUNC_NAME
                value: "getVideosAndUpdateDB"
              - name: FUNC_PARAM
                value: "?&channelId=UCcA88_Z7wQWMoQ9bKwjuanA&part=snippet&type=video&order=date&maxResults=5"
              - name: LIB_NAME
                value: "youtube"
            envFrom:
              - configMapRef:
                  name: firebase
              - configMapRef:
                  name: youtube-api-key-4
          restartPolicy: OnFailure
          hostNetwork: true
