apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: koreanow-channel-info
spec:
  schedule: "0 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: koreanow-channel-info
            image: gcr.io/dongdongchat/youtube-cron-job
            env:
              - name: FUNC_NAME
                value: "getChannelDetailsAndUpdateDB"
              - name: FUNC_PARAM
                value: "?part=snippet,brandingSettings,statistics&id=UCR-L8oZkHzgDh1ahJhH2WDQ"
              - name: LIB_NAME
                value: "youtube"
            envFrom:
            - configMapRef:
                name: firebase
            - configMapRef:
                name: youtube-api-key-1
          restartPolicy: OnFailure
          hostNetwork: true
   