apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: koreanunnie-live-videos
spec:
  schedule: "* * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: koreanunnie-live-videos-0
            image: gcr.io/dongdongchat/youtube-cron-job
            env:
              - name: FUNC_NAME
                value: "getVideosAndUpdateDB"
              - name: FUNC_PARAM
                value: "?channelId=UCcA88_Z7wQWMoQ9bKwjuanA&part=snippet&type=video&eventType=live"
              - name: LIB_NAME
                value: "youtube"
              - name: FIREBASE_DATABASE_URL
                value: https://dongdongchat.firebaseio.com
            envFrom:
              - configMapRef:
                  name: firebase
              - configMapRef:
                  name: youtube-api-key-1
          restartPolicy: OnFailure
          hostNetwork: true
