apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: word-of-the-day
spec:
  schedule: "0 23 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: word-of-the-day
            image: gcr.io/jinjaio/youtube-cron-job
            env:
              - name: FUNC_NAME
                value: "getWord"
              - name: LIB_NAME
                value: "wod"
            envFrom:
              - configMapRef:
                  name: firebase
          restartPolicy: OnFailure
          hostNetwork: true
